luftqualitaet_sachsen/config/urls.py
from django.conf import settings
from django.views.generic import TemplateView
from django.conf.urls import include, patterns, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'luftqualitaet_sachsen.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('measuring_stations.urls')),
    url(r'^impressum/', TemplateView.as_view(template_name='impressum.html'), name='impressum')
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

luftqualitaet_sachsen/measuring_stations/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.views.generic import TemplateView
from rest_framework import routers

from measuring_stations import views


router = routers.DefaultRouter()
router.register(r'measuringpoint_overview', views.MeasuringPointView)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^$', views.overview, name='measuring_stations_measuringpoint_overview'),
    url(r'^station/(?P<slug>[-\w]+)/$', views.MeasuringPointDetailView.as_view(),
        name='measuring_stations_measuringpoint_detail'),
    url(r'^station/(?P<slug>[-\w]+)\.csv$', views.MeasuringPointCSVView.as_view(),
        name='measuring_stations_measuringpoint_csv'),
    url(r'^erklaerung/$', TemplateView.as_view(
        template_name='measuring_stations/explaination.html'), name='explaination')
]

luftqualitaet_sachsen/measuring_stations/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import csv

from django.apps import apps
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from geoposition.fields import GeopositionField
from uuidfield import UUIDField
from easy_thumbnails.fields import ThumbnailerImageField
from pytz.exceptions import NonExistentTimeError
from django.utils import timezone
from dateutil import parser

from . import managers


class ValueFields(models.Model):
    value_fields = ('so2', 'no', 'no2', 'o3', 'ben', 'pm10_teom', 'pm10', 'pm25', 'ec', 'oc',
        'sti', 'stns', 'met', 'co', 'pm10_pb')

    class Meta:
        abstract = True

    @classmethod
    def get_verbose_names(cls, fields):
        return tuple([cls._meta.get_field(field).verbose_name for field in fields])


@python_2_unicode_compatible
class MeasuringPoint(ValueFields):
    EU_TYPING_CITY_BACKGROUND = 1
    EU_TYPING_CITY_TRAFFIC = 2
    EU_TYPING_SUBURBAN = 3
    EU_TYPING_RURAL_CLOSE_TO_CITY = 4
    EU_TYPING_RURAL = 5
    EU_TYPING_RURAL_BACKGROUND = 6
    EU_TYPING_HEIGHT_STATION = 7
    EU_TYPING_CHOICES = (
        (EU_TYPING_CITY_BACKGROUND, 'städtischer Hintergrund'),
        (EU_TYPING_CITY_TRAFFIC, 'städtisch/Verkehr'),
        (EU_TYPING_SUBURBAN, 'vorstädtisches Gebiet'),
        (EU_TYPING_RURAL_CLOSE_TO_CITY, 'ländlich, stadtnah'),
        (EU_TYPING_RURAL, 'ländlich'),
        (EU_TYPING_RURAL_BACKGROUND, 'ländlicher Hintergrund'),
        (EU_TYPING_HEIGHT_STATION, 'Höhenstation'),
    )
    CATEGORY_LOCAL = 1
    CATEGORY_CITY = 2
    CATEGORY_TRAFFIC = 3
    CATEGORIES = (
        (CATEGORY_LOCAL, 'Stationen zur Beurteilung der regionalen Vorbelastung'),
        (CATEGORY_CITY, 'Stationen zur Beurteilung der allgemeinen städtischen Belastung'),
        (CATEGORY_TRAFFIC, 'Stationen zur Beurteilung verkehrsnaher Belastungen'),
    )
    name = models.CharField('Name', max_length=100, unique=True)
    slug = models.SlugField(unique=True)
    form_id = models.IntegerField('Formular ID', unique=True)
    location = models.CharField('Standort', max_length=100,
        help_text='Straße bzw. ungefähren Standort angeben')
    city = models.CharField('Stadt', max_length=100, help_text='Stadt oder Ortschaft angeben')
    amsl = models.IntegerField('Höhe über NN [m]', blank=True, null=True)
    eu_typing = models.IntegerField('Typisierung nach EU-Richtlinie', choices=EU_TYPING_CHOICES,
        default=EU_TYPING_CITY_BACKGROUND)
    category = models.IntegerField('Kategorie', choices=CATEGORIES, default=CATEGORY_CITY)
    image = ThumbnailerImageField('Bild', upload_to='measuring_stations', blank=True)
    position = GeopositionField()
    so2 = models.BooleanField('SO2', default=False)
    no = models.BooleanField('NO', default=False)
    no2 = models.BooleanField('NO2', default=False)
    o3 = models.BooleanField('O3', default=False)
    ben = models.BooleanField('BEN', default=False)
    pm10_teom = models.BooleanField('PM10TEOM', default=False)
    pm10 = models.BooleanField('PM10', default=False)
    pm25 = models.BooleanField('PM2.5', default=False)
    ec = models.BooleanField('EC', default=False)
    oc = models.BooleanField('OC', default=False)
    sti = models.BooleanField('STI', default=False)
    stns = models.BooleanField('STNS', default=False)
    met = models.BooleanField('MET', default=False)
    co = models.BooleanField('CO', default=False)
    pm10_pb = models.BooleanField('PM10 Pb', default=False)

    objects = managers.MeasuringPointManager()

    class Meta:
        verbose_name = 'Messstelle'
        verbose_name_plural = 'Messstellen'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('measuring_stations_measuringpoint_detail', kwargs={'slug': self.slug})

    def natural_key(self):
        return (self.name,)

    def get_csv(self, csvfile, limit, flat=False):
        writer = csv.writer(csvfile, lineterminator='\n')
        model = apps.get_model('measuring_stations', 'IndicatedValue')
        if flat:
            writer.writerow(("x", ""))
            names = model.get_verbose_names(self.active_values)
            values = self.indicated_values.values_list(*self.active_values)[:limit][0]
            writer.writerows(zip(names, values))
        else:
            csv_fields = ('date_created',) + self.active_values
            writer.writerow(model.get_verbose_names(csv_fields))
            writer.writerows(self.indicated_values.values_list(*csv_fields)[:limit])
        return csvfile

    def put_csv(self, content, unit, form_id, station_name):
        reader = csv.DictReader(content, delimiter=b';')
        print station_name
        try:
            station = MeasuringPoint.objects.get(form_id=form_id)
        except MeasuringPoint.DoesNotExist:
            self.stderr.write(u'MeasuringPoint "{0}"" not found'.format(station_name))
            return
        unit_key = unit.lower().replace('.', '')
        for row in reader:
            dateRow = row.get('Datum Zeit', '')
            if len(dateRow):
                try:
                    date = parser.parse(dateRow, dayfirst=True)
                    if timezone.is_naive(date):
                        try:
                            date = timezone.make_aware(date, self.tz)
                        except NonExistentTimeError as e:
                            self.stderr.write(str(e))
                except ValueError:
                    self.stderr.write('Failed to parse date "{0}"'.format(dateRow))
                    continue

                value = row[(' ' + station_name + ' ' + unit).encode('iso-8859-1')].strip()

                if value.find(',') > -1:
                    value = float(value.replace(',', '.'))
                is_float = isinstance(value, float)
                if is_float or (value.find('g/m') == -1 and value.find('n. def.') == -1):
                    IndicatedValue.objects.update_or_create(date_created=date,
                                measuring_point=station, defaults={unit_key: float(value)})

    @property
    def active_values(self):
        return tuple([field for field in self.value_fields if getattr(self, field)])

    def active_names(self):
        return ', '.join(self.get_verbose_names(self.active_values))
    active_names.short_description = 'Angezeigte Messwerte'


@python_2_unicode_compatible
class IndicatedValue(ValueFields):
    uuid = UUIDField(auto=True, primary_key=True)
    date_created = models.DateTimeField('Datum')
    measuring_point = models.ForeignKey(MeasuringPoint, related_name='indicated_values',
        verbose_name='Messstelle')
    so2 = models.FloatField('SO2', default=0)
    no = models.FloatField('NO', default=0)
    no2 = models.FloatField('NO2', default=0)
    o3 = models.FloatField('O3', default=0)
    ben = models.FloatField('BEN', default=0)
    pm10_teom = models.FloatField('PM10TEOM', default=0)
    pm10 = models.FloatField('PM10', default=0)
    pm25 = models.FloatField('PM2.5', default=0)
    ec = models.FloatField('EC', default=0)
    oc = models.FloatField('OC', default=0)
    sti = models.FloatField('STI', default=0)
    stns = models.FloatField('STNS', default=0)
    met = models.FloatField('MET', default=0)
    co = models.FloatField('CO', default=0)
    pm10_pb = models.FloatField('PM10 Pb', default=0)

    class Meta:
        verbose_name = 'Messwert'
        verbose_name_plural = 'Messwerte'
        ordering = ['-date_created']
        unique_together = ('date_created', 'measuring_point')

    def __str__(self):
        return '%s %s' % (self.date_created, self.measuring_point)

luftqualitaet_sachsen/measuring_stations/views.py
from django.http import HttpResponse
from django.views.generic import DetailView
from django.shortcuts import render
from geopy import distance
from rest_framework import viewsets
from rest_framework.response import Response

from .models import MeasuringPoint
from. import serializers


def overview(request):
    ctx = {'measuring_points': MeasuringPoint.objects.all()}
    return render(request, 'measuring_stations/overview.html', ctx)


class MeasuringPointDetailView(DetailView):
    model = MeasuringPoint

    def nearest_stations(self):
        results = []
        for station in self.model.objects.exclude(slug=self.object.slug):
            d = distance.distance(
                (self.object.position.latitude, self.object.position.longitude),
                (station.position.latitude, station.position.longitude)
            )
            results.append({'distance': d, 'obj': station})
        results = sorted(results, key=lambda k: k['distance'])
        return results[:5]


class MeasuringPointCSVView(DetailView):
    model = MeasuringPoint

    def render_to_response(self, context, **response_kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="%s.csv"' % self.object.slug

        return self.object.get_csv(response, self.request.GET.get('limit', 50),
            bool(int(self.request.GET.get('flat', 0))))


class MeasuringPointView(viewsets.ReadOnlyModelViewSet):
    queryset = MeasuringPoint.objects.all()

    def list(self, request):
        qs = self.get_queryset()
        serializer = serializers.MiniMeasuringPointSerializer(
            qs, context={'request': request}, many=True)
        return Response(serializer.data)

    def retrieve(self, request, pk=None):
        qs = self.get_queryset().filter(pk=pk).prefetch_related('indicated_values').last()
        serializer = serializers.MeasuringPointSerializer(qs, context={'request': request})
        return Response(serializer.data)

luftqualitaet_sachsen/measuring_stations/templates/measuring_stations/_marker.html
<div class="row hidden" id="marker-template">
  <div class="col-md-5">
    <a href="">Messstelle <span class="station-name"></span></a><br>
    <span class="location"></span>, <span class="city"></span><br>
    <span class="amsl"></span> m über NN<br>
    <span class="category"></span>
    <img src="" alt="Foto der Messstelle" class="thumbnail hidden">
  </div>
  <div class="col-md-7">
    <div class="chart"></div>
  </div>
</div>

luftqualitaet_sachsen/measuring_stations/templates/measuring_stations/explaination.html
{% extends 'base.html' %}

{% load static %}

{% block js %}
    {{ block.super }}
    <script src="{% static "js/explaination.js" %}"></script>
    <script type="text/javascript">
        window.explainationsJsonUrl = "{% static 'explainations.json' %}";
    </script>
{% endblock js %}
{% block content %}

<h1>Messwerte</h1>

<div class="panel-group" id="explain-list" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default hidden" id="template">
        <div class="panel-heading">
            <h3 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne"></a>
            </h3>
        </div>
        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
                Panel content
            </div>
        </div>
    </div>
</div>
{% endblock content %}

luftqualitaet_sachsen/measuring_stations/templates/measuring_stations/home.html
{% extends "base.html" %}

{% load leaflet_tags static %}

{% block css %}
    {{ block.super }}
    <style>
        .leaflet-container {  /* all maps */
            width:  100%;
            height: 500px;
        }
    </style>
    {% leaflet_css %}
{% endblock css %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        window.addEventListener("map:init", function (e) {
            var detail = e.detail;
            {% for marker in measuring_points %}
                {% if marker.position.latitude %}
                    L.marker([{{ marker.position.latitude }}, {{ marker.position.longitude }}])
                        .addTo(detail.map).bindPopup(
                            "<p>{{ marker.name }}</p>"
                            + "<p>{{ marker.location }}</p>{% if marker.image %}"
                            + "<img src=\"{% static marker.image %}\"> {% endif %}"
                            + "<p>{{ marker.amsl }}</p>"
                            + "<p>{{ marker.get_eu_typing_display }}</p>"
                            + "<p>{{ marker.get_category_display }}</p>"
                    );
                {% endif %}
            {% endfor %}
        }, false);
    </script>
    {% leaflet_js %}
{% endblock js %}

{% block content %}
    <div class="content">
        <h1>Übersicht</h1>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
            dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.
            Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
            Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore
            et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.
            Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
        {% leaflet_map "start_map" %}
    </div>
{% endblock content %}

luftqualitaet_sachsen/measuring_stations/templates/measuring_stations/measuringpoint_detail.html
{% extends "base.html" %}

{% load l10n %}
{% load leaflet_tags %}
{% load static from staticfiles %}
{% load thumbnail %}

{% block css %}
    {{ block.super }}
    <link href="{% static "c3.css" %}" rel="stylesheet" type="text/css">
    {% if measuringpoint.position.latitude %}
        {% leaflet_css %}
    {% endif %}
{% endblock css %}

{% block js_head %}
    {{ block.super }}
    <script src="{% static "d3.min.js" %}"></script>
    <script src="{% static "c3.min.js" %}"></script>
{% endblock js_head %}

{% block js %}
    {{ block.super }}
    <script src="{% static "ekko-lightbox.min.js" %}"></script>
    <script>
        $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
            event.preventDefault();
            $(this).ekkoLightbox();
        });
    </script>
    {% if measuringpoint.position.latitude %}
        {% leaflet_js %}
        <script>
            window.addEventListener("map:init", function (e) {
                {% localize off %}
                var lat = {{ measuringpoint.position.latitude }};
                var lng = {{ measuringpoint.position.longitude }};
                {% endlocalize %}
                var center = new L.LatLng(lat, lng);
                var detail = e.detail;
                detail.map.setView(center, 14);
                L.marker([lat, lng]).addTo(detail.map);
            }, false);
        </script>
        {% leaflet_map "measuringpointmap" callback="window.map_init_basic" %}
    {% endif %}
{% endblock js %}

{% block content %}
    <h1>{{ measuringpoint.name }}<br>
        <small>{{ measuringpoint.get_category_display }}</small></h1>
    <div class="row">
        <div class="col-md-8">
            <div id="chart"></div>
            <script>
                var chart = c3.generate({
                    bindto: '#chart',
                    data: {
                        url: '{% url "measuring_stations_measuringpoint_csv" slug=object.slug %}',
                        x: 'Datum',
                        xFormat: '%Y-%m-%d %H:%M:%S+00:00',
                    },
                    axis: {
                        x: {
                            type: 'timeseries',
                            tick: {
                                format: '%d.%m.%Y %H:%M',
                                rotate: 10,
                            },
                        },
                        y: {
                            label: {
                                text: 'µg/m³',
                                position: 'outer-middle',
                            },
                        }
                    },
                    subchart: {
                        show: true,
                    },
                    legend: {
                        position: 'right',
                    },
                });
            </script>
            <p><a href="{% url 'explaination' %}">Werte Erlärung</a></p>
        </div>

        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">Informationen zur Messstelle</div>
                <div class="panel-body">
                    {% if measuringpoint.image %}
                        <a href="{{ MEDIA_URL }}{{ measuringpoint.image }}" data-toggle="lightbox" data-title="Messstelle {{ measuringpoint.name }}" class="thumbnail">
                            <img src="{{ measuringpoint.image|thumbnail_url:'detail' }}" alt="Foto der Messstelle" class="img-responsive">
                        </a>
                    {% endif %}
                    <table class="table table-condensed">
                        <tr>
                            <td>Standort:</td>
                            <td>{{ measuringpoint.location }}, {{ measuringpoint.city }}</td>
                        </tr>
                        <tr>
                            <td>Höhe über NN:</td>
                            <td>{{ measuringpoint.amsl }} m</td>
                        </tr>
                        <tr>
                            <td>Typisierung nach EU-Richtlinie:</td>
                            <td>{{ measuringpoint.get_eu_typing_display }}</td>
                        </tr>
                    </table>
                    {% if measuringpoint.position.latitude %}
                        {% leaflet_map "measuringpointmap" %}
                    {% endif %}
                </div>
                <div class="panel-footer">
                    Nächstgelegene Stationen
                </div>
                <div class="panel-body">
                    <table class="table table-condensed">
                        {% for station in view.nearest_stations %}
                            <tr>
                                <td><a href="{% url "measuring_stations_measuringpoint_detail" station.obj.slug %}">{{ station.obj.name }}</a></td>
                                <td><a href="{% url "measuring_stations_measuringpoint_detail" station.obj.slug %}">{{ station.distance.km|floatformat }} km</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

luftqualitaet_sachsen/measuring_stations/templates/measuring_stations/overview.html
{% extends "base.html" %}

{% load static l10n %}

{% block css %}
    {{ block.super }}
    <link href="{% static "c3.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "mapbox.css" %}" rel="stylesheet" type="text/css">
    <style>
        .leaflet-container {  /* all maps */
            width:  100%;
            height: 600px;
        }
    </style>
{% endblock css %}

{% block js %}
    {{ block.super }}
    <script src="{% static "mapbox.js" %}"></script>
    <script src="{% static "d3.min.js" %}"></script>
    <script src="{% static "c3.min.js" %}"></script>
    <script src="{% static "js/overview.js" %}"></script>
{% endblock js %}

{% block title %}Übersicht{% endblock %}

{% block content %}
    <div class="content">
        <p>Das Projekt <strong>Luftqualität Sachsen</strong> stellt die Messwerte des <a href="http://www.smul.sachsen.de/lfulg/">Sächsischen Landesamtes für Umwelt, Landwirtschaft und Geologie</a> übersichtlich dar. Es ist im Rahmen der Arbeit im <a href="http://codefor.de/leipzig/">OK Lab Leipzig</a> entstanden.</p>
        <div id="start_map"></div>
        <div class="container">
            {% for marker in measuring_points %}
                {% if marker.image %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
  {% include 'measuring_stations/_marker.html' %}
{% endblock content %}